---
- hosts: localhost
  become: yes
  roles:
   - ec2
  tasks:
  - name: get the public IP of Bastion server
    ec2_instance_facts:
      region: "{{ region }}"
      filters:
        "tag:Name": Bastion-test
    register: ec2info
  - name: Display ec2info
    debug: var="ec2info.instances[0].public_ip_address"
  - name: add a host to the inventory
    lineinfile:
      path: /etc/ansible/hosts
      line: 'host1 ansible_ssh_host={{ec2info.instances[0].public_ip_address}} ansible_ssh_port=1922'
      insertbefore: BOF
